// env.d.ts
namespace NodeJS {
	interface ProcessEnv {
		AUTH_COOKIE_NAME: string;
		AUTH_COOKIE_SIGNATURE_KEY_CURRENT: string;
		AUTH_COOKIE_SIGNATURE_KEY_PREVIOUS: string;

		NEXT_PUBLIC_FIREBASE_API_KEY: string;
		NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
		NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
		NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
		NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
		NEXT_PUBLIC_FIREBASE_APP_ID: string;
		NEXT_PUBLIC_FIREBASE_APP_MEASUREMENT_ID: string;
		NEXT_PUBLIC_VAPID_PUBLIC_KEY: string;
		RECRAFT_API_TOKEN: string;

		FIREBASE_CLIENT_EMAIL: string;
		FIREBASE_PRIVATE_KEY: string;
		FIREBASE_PROJECT_ID: string;

		RECRAFT_API_STYLE: string;
		GEMINI_API_TOKEN: string;
		NEXT_PUBLIC_COMMIT_HASH: string;
		NEXT_PUBLIC_BACKEND_URL: string;

		OPEN_API_TOKEN: string;
	}
}
