// env.d.ts
namespace NodeJS {
	interface ProcessEnv {
		AUTH_COOKIE_NAME: string;

		NEXT_PUBLIC_FIREBASE_API_KEY: string;
		NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
		NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
		NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
		NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
		NEXT_PUBLIC_FIREBASE_APP_ID: string;

		NEXT_PUBLIC_COMMIT_HASH: string;
		NEXT_PUBLIC_BACKEND_URL: string;
	}
}
